services:
  mongo:
    build:
      dockerfile: containers/mongo.dockerfile
    ports:
      - "21017:21017"
  
  app:
    build: 
      context: .
      dockerfile: containers/app.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - "containers/app.env"